added safety checks to context processor
mpasternak/django-password-policies pull request #11
Opened 2021-07-02 15:59 UTC by kostrom

I added some safety checks to prevent this context processor from raising an unnecessary exception.
rest_framework can set user = None
django.contrib.auth.context_processors.auth is okay with that as long as an attribute exists

2021-07-09 07:39 UTC, mpasternak requested changes
Please add at least one failing test-case for the added functionality

2021-07-15 15:41 UTC, kostrom commented
Sorry for the late reply. I was on vacation. I can do that.

2021-07-15 21:02 UTC, kostrom commented
My reproduction involves a REST_FRAMEWORK setting, but I don't want to add that to the requirements to run a test.
I'm trying to mock out some of that, but might not get it today.

2021-07-16 19:23 UTC, kostrom commented
Sorry, I'm not able to get a working request with a middleware override, that also recreates these same conditions.

My fix is essentially just a basic "Check for None before you use the object."

The use case is admittedly not good practice, and I may have corrected the underlying problem that led to this, but if someone has those problems, you want them to run into problems in their code, not in your middleware.

2021-07-19 16:28 UTC, mpasternak commented
Ok. I reviewed the change and I see where's the problem. What is exact configuration you're running this on (if that's not a secret, of course)? From what I understand, your REST framework doesn't set "user" attribute on the "request". 

On the other hand, why would you want to use django-password-policies with REST framework views? I guess your REST framework has it's own authentication mechanisms... my question is because I believe django-password-policies is somewhat an "interactive" package, while REST API is... an API. If I'd do that, my REST API would return some 4xx error with "Password Expired" message or something like that. 

Let's discuss.

2021-07-27 16:05 UTC, kostrom commented
There's an interactive page, and there's an api. I actually redid the request from scratch because I forgot about this for a while -- sorry about that. And yes, the specific configuration which led to the problem was itself an error -- but password policies shouldn't mask it by raising its own exceptions when we can easily prevent that. (closing this one)

2021-07-27 16:05 UTC, closed without merging